### ISSUE TITLE
add github_token permissions needed for github actions

### ISSUE THREAD

**Issue by miparnisari** [semgrep/semgrep-docs#952]
https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions

can you please change the samples to include the permissions that the workflows need?

```yaml
# Name of this GitHub Actions workflow.
name: Semgrep

on:
  ...

permissions:
   contents: read

jobs:
  semgrep:
      ...
```
